set_player_profile: 0x0093E690
get_player_name: 0x0274A620
get_char_info: 0x030BD860
css_bg_init: 0x00B3D3D0
update_char_color: 0x01D82D00
local_done_char_select: 0x02F919A0
take_damage: 0x01D1A5B0
init_main_menu_text: 0x009DD180
get_stage_dest: 0x01E3DB40
init_stage_camera: 0x01E4EF50
death_update: 0x007454B0
game_end: 0x030D7C00
draw_end_game_text: 0x01E8D710
get_player_stocks: 0x00886320
get_player_damage: 0x00885EB0
is_player_active: 0x02748D00
get_player_color: 0x886F00

debug: false

port_tcp: 4343
port_udp: 6500